# 1. ä¸ºå·¥ä½œæµå®šä¹‰åå­—
name: Vue build for github pages

# 2. è§¦å‘æ¡ä»¶ä¿®æ”¹ä¸º: å½“ main æˆ– master åˆ†æ”¯, æœ‰ push çš„æ—¶å€™, æ‰§è¡Œä»»åŠ¡
on:
  push:
    branches:
      - vue3
  # è¿™ä¸ªé€‰é¡¹å¯ä»¥ä½¿ä½ æ‰‹åŠ¨åœ¨ Action tab é¡µé¢è§¦å‘å·¥ä½œæµ
  workflow_dispatch:

# è®¾ç½® GITHUB_TOKEN çš„æƒé™ï¼Œä»¥å…è®¸éƒ¨ç½²åˆ° GitHub Pagesã€‚
permissions:
  contents: read
  pages: write
  id-token: write

# å…è®¸ä¸€ä¸ªå¹¶å‘çš„éƒ¨ç½²
concurrency:
  group: 'pages'
  cancel-in-progress: true

# 3. åˆ›å»ºå·¥ä½œæµ
jobs:
  deploy:  #å•æ¬¡éƒ¨ç½²çš„å·¥ä½œæè¿°
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest    # ä¾èµ–çŽ¯å¢ƒ

    steps:                    # å·¥ä½œæµæ­¥éª¤
      # step 1. èŽ·å–æºç , æ‹‰å–ä»“åº“ä»£ç 
      - name: Checkout ðŸ›Žï¸             # æ­¥éª¤å
        uses: actions/checkout@v3 # ä½¿ç”¨æ’ä»¶ => https://github.com/actions/checkout

      # step 2. ä½¿ç”¨æŒ‡å®šç‰ˆæœ¬ node
      - name: Use Node  ðŸ“¦              # æ­¥éª¤å
        uses: actions/setup-node@v3 # ä½¿ç”¨æ’ä»¶ => https://github.com/actions/setup-node
        with: # æ’ä»¶æºå¸¦å‚æ•°
          node-version: 16 # æŒ‡å®š node ç‰ˆæœ¬
          cache: 'npm'
      # step 3. å®‰è£…ä¾èµ–å¹¶æ‰“åŒ…
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload dist repository
          path: './build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2    #ä½¿ç”¨æ’ä»¶ => https://github.com/actions/deploy-pages
